"""Stable protocol isolating business logic from thermodynamic implementations."""

from typing import Protocol

from schemas.domain import CalculationResult, TaskManifest


class ThermodynamicBackend(Protocol):
    def bubble_point(self, request: TaskManifest) -> CalculationResult: ...

    def dew_point(self, request: TaskManifest) -> CalculationResult: ...

    def isobaric_vle(self, request: TaskManifest) -> CalculationResult: ...

    def isothermal_vle(self, request: TaskManifest) -> CalculationResult: ...

    def tp_flash(self, request: TaskManifest) -> CalculationResult: ...

    def phase_stability(self, request: TaskManifest) -> CalculationResult: ...

    def azeotrope(self, request: TaskManifest) -> CalculationResult: ...

    def lle(self, request: TaskManifest) -> CalculationResult: ...
